<?php

class PaylineProviderTest extends TestCase
{
    /**
     * @var \Laratalks\PaymentGateways\Providers\Rest\PaylineProvider
     */
    protected $provider;
    public function setUp()
    {
        $this->provider = new \Laratalks\PaymentGateways\Providers\Rest\PaylineProvider(require __DIR__ . '/../../config/payment-gateway.php');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCallPaymentRequest()
    {
        $this->provider->callPaymentRequest(new \Laratalks\PaymentGateways\ValueObjects\PaymentRequestNeeds(1000, 'http://localhost'));


    }
}