<?php

use Laratalks\PaymentGateways\Providers\Soap\ZarinpalProvider;
use Laratalks\PaymentGateways\ValueObjects\PaymentRequestNeeds;

class ZarinpalProviderTest extends TestCase
{
    /**
     * @var ZarinpalProvider
     */
    protected $provider;

    public function setUp()
    {
        $configs = require __DIR__ . '/../../config/payment-gateway.php';
        $this->provider = new ZarinpalProvider($configs);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @expectedException \Laratalks\PaymentGateways\Exceptions\PaymentGatewayBadRequestException
     */
    public function testCallAndGetReturnUrlExceptedException()
    {
        $needs = new PaymentRequestNeeds(1000, 'http://localhost/');
        $needs->set('description', 'something');
        
        $paymentResponse = $this->provider->callPaymentRequest($needs);
    }
}